Feature/kanban board
qa3aq/TaskManager pull request #15
Opened 2021-12-11 09:38 UTC by qa3aq

2021-12-11 19:46 UTC, greybutton requested changes

2021-12-11 19:46 UTC, greybutton commented on app/javascript/packs/application.js
> +import WebpackerReact from 'webpacker-react';
не вижу добавленного гема

2021-12-12 06:31 UTC, qa3aq commented on app/javascript/packs/application.js
> +import WebpackerReact from 'webpacker-react';
> не вижу добавленного гема

гем добавил.
после этого задания доску должно быть видно? у меня пустая страница.

2021-12-12 16:49 UTC, greybutton commented on app/javascript/packs/application.js
> +import WebpackerReact from 'webpacker-react';
да, должно быть видно. может быть гем не верно поставил, должен еще нпм пакет webpacker-react добавится

2021-12-14 09:43 UTC, qa3aq commented on app/javascript/packs/application.js
> +import WebpackerReact from 'webpacker-react';
теперь видно)

2021-12-14 11:14 UTC, greybutton approved these changes

2021-12-15 00:03 UTC, merged