Feature/tasks
qa3aq/TaskManager pull request #16
Opened 2021-12-21 11:10 UTC by qa3aq

2021-12-22 16:27 UTC, greybutton requested changes

2021-12-22 16:27 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(id: :desc)
ордер не задается в контроллере

2021-12-22 16:27 UTC, greybutton commented on app/javascript/forms/TaskForm
> +import { pick, propOr } from 'ramda';
у файла расширение потерялось

2021-12-23 08:04 UTC, qa3aq commented on app/controllers/api/v1/tasks_controller.rb
> +      order(id: :desc)
> ордер не задается в контроллере

почему не задается? не нащел информации почему нельзя в контроллере задавать.

2021-12-23 17:45 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(id: :desc)
сортировка это параметр который может меняться динамически, задав его в контроллере нельзя будет в запросе указать сортировку, будет срабатывать всегда сортировка из контроллера

2021-12-23 17:45 UTC, greybutton approved these changes

2021-12-24 01:28 UTC, qa3aq commented on app/controllers/api/v1/tasks_controller.rb
> +      order(id: :desc)
Понял, спасибо!

2021-12-24 01:28 UTC, merged