Feature/coveralls
qa3aq/TaskManager pull request #20
Opened 2022-01-08 15:53 UTC by qa3aq

2022-01-10 07:35 UTC, greybutton requested changes

2022-01-10 07:35 UTC, greybutton commented on .coveralls.yml
> +repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}
это вроде в github actions надо делать

2022-01-10 07:35 UTC, greybutton commented on test/test_helper.rb
> +Coveralls.wear!
генерировать покрытие нужно только в CI

2022-01-10 07:45 UTC, qa3aq commented on .coveralls.yml
> +repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}
> это вроде в github actions надо делать

в этом задании

"Прикрутить к проекту Coveralls

https://github.com/colszowka/simplecov

https://coveralls.io/

Добавить COVERALLS_REPO_TOKEN с помощью GA environment secrets

Добавить бейдж в Readme проекта на гитхабе"

2022-01-10 20:21 UTC, greybutton commented on .coveralls.yml
> +repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}
думаю это надо добавлять в .github/workflows/main.yml и проверить настройки проекта, что секрет передается. В чеках должен появится coveralls чекер, так же как сейчас гитхаб экшенс чекер "Main / build"

2022-01-12 19:12 UTC, greybutton approved these changes

2022-01-13 05:30 UTC, merged