Feature/models
qa3aq/TaskManager pull request #5
Opened 2021-11-18 07:20 UTC by qa3aq

2021-11-18 18:52 UTC, greybutton requested changes

2021-11-18 18:52 UTC, greybutton commented on test/models/task_test.rb
> +  # end
не дописан тест

2021-11-18 18:52 UTC, greybutton commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
почему эти изменения здесь?

2021-11-18 18:52 UTC, greybutton commented on config/initializers/simple_form.rb
> +    # and required attributes
этот файл не нужен

2021-11-18 18:52 UTC, greybutton commented on config/locales/simple_form.en.yml
> +    #     password: 'Password'
этот файл не нужен

2021-11-18 18:52 UTC, greybutton commented on lib/templates/erb/scaffold/_form.html.erb
> +    <%%= f.button :submit %>
этот файл не нужен

2021-11-19 05:47 UTC, qa3aq commented on config/database.yml
> +  database: <%= ENV['DATABASE_NAME'] || 'task_manager_development' %>
криво смержил, вроде бы поправил

2021-11-19 16:25 UTC, greybutton requested changes
> Merge branch 'develop' into feature/models
таких коммитов быть не должно, если нужен код из девелопа, нужно делать ребейс, а не мердж

отребейси ветку feature/models от develop

2021-11-19 17:12 UTC, qa3aq commented
> 

у меня были конфликты в 3х файлах, я их тут на гитхабе поправил. мне сейчас, как лучше сделать, претащить этот коммит в локал и там ребейзить или тут можно как-то это сделать?

2021-11-19 17:20 UTC, qa3aq commented
> > Merge branch 'develop' into feature/models
> > таких коммитов быть не должно, если нужен код из девелопа, нужно делать ребейс, а не мердж
> 
> отребейси ветку feature/models от develop
у меня были конфликты в 3х файлах, я их тут на гитхабе поправил. мне сейчас, как лучше сделать, претащить этот коммит в локал и там ребейзить или тут можно как-то это сделать?

2021-11-19 17:41 UTC, greybutton commented
локально отребейзить ветку от девелопа и запушить с форсом

2021-11-19 18:02 UTC, qa3aq commented
> локально отребейзить ветку от девелопа и запушить с форсом

вернул, как было, до того как кофликты поправил

2021-11-21 19:29 UTC, greybutton commented
> вернул, как было, до того как конфликты поправил
этого не достаточно

1 спуллить с ребейсом изменения в ветке develop
2 отребейзить ветку feature/models от develop ветки (если конфликты, то разрешить их локально)
3 зафорспушить ветку feature/models

2021-11-22 15:44 UTC, greybutton approved these changes

2021-11-22 15:53 UTC, merged